---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - skjaif.skjaiferator.no
  resources:
  - svartskjaifs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skjaif.skjaiferator.no
  resources:
  - svartskjaifs/finalizers
  verbs:
  - update
- apiGroups:
  - skjaif.skjaiferator.no
  resources:
  - svartskjaifs/status
  verbs:
  - get
  - patch
  - update
